### PR TITLE
Support utf-8 strings

### PR DESCRIPTION
**Pull request by pashaie**
using qrcode_UTF8.js from
https://github.com/kazuhikoarase/qrcode-generator,

### CODE REVIEW

**Comment by Delagen** [comment]
+1

**Comment by Delagen** [comment]
Solved due manual combine original project with _utf.js file and src/jquery-qrcode.js
I think it is more usefull way. because of separate update of wrapper and common library

**Comment by lrsjng** [comment]
added in 0.12.0

**Comment by pashaie** [comment]
tnx

**Pull request closed without merging**
